### ISSUE TITLE
Crash on multitouch SwipeLayout

### ISSUE THREAD

**Issue by baptistejamin** [Malinskiy/SuperRecyclerView#101]
Hi!

I'm facing a crash "java.lang.ArrayIndexOutOfBoundsException" on ViewDragHelper when doing multitouch swipe.

Anybody faced this issue?

**Comment by iTomkinas** [comment]
yep, same for me

**Comment by djonus** [comment]
Indeed, upset emoji...

**Comment by Ainiuso** [comment]
Got the same one. Please fix.

`Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
       at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1014)
       at android.support.v4.widget.DrawerLayout.onInterceptTouchEvent(DrawerLayout.java:1430)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2284)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2683)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2399)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2683)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2399)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2683)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2399)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2683)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2399)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2683)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2399)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2683)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2399)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2552)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1767)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2840)`
