### ISSUE TITLE
Header adapter example refresh NullPointerException

### ISSUE THREAD

**Issue by ayyb1988** [Malinskiy/SuperRecyclerView#48]
Process: com.malinskiy.superrecyclerview.sample, PID: 15174
    java.lang.NullPointerException
            at com.eowise.recyclerview.stickyheaders.HeaderStore.wasHeader(HeaderStore.java:98)
            at com.eowise.recyclerview.stickyheaders.StickyHeadersItemDecoration.getItemOffsets(StickyHeadersItemDecoration.java:89)
            at android.support.v7.widget.RecyclerView.getItemDecorInsetsForChild(RecyclerView.java:2744)
            at android.support.v7.widget.RecyclerView$LayoutManager.measureChildWithMargins(RecyclerView.java:5543)
            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1332)
            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1269)
            at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:523)
            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:1942)
            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2237)
            at android.view.View.layout(View.java:14884)
            at android.view.ViewGroup.layout(ViewGroup.java:4651)
            at android.support.v4.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:543)
            at android.view.View.layout(View.java:14884)
            at android.view.ViewGroup.layout(ViewGroup.java:4651)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
            at android.view.View.layout(View.java:14884)
            at android.view.ViewGroup.layout(ViewGroup.java:4651)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:14884)
            at android.view.ViewGroup.layout(ViewGroup.java:4651)
            at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
            at android.view.View.layout(View.java:14884)
            at android.view.ViewGroup.layout(ViewGroup.java:4651)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:14884)
            at android.view.ViewGroup.layout(ViewGroup.java:4651)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1694)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1548)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1457)
            at android.view.View.layout(View.java:14884)
            at android.view.ViewGroup.layout(ViewGroup.java:4651)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:14884)
            at android.view.ViewGroup.layout(ViewGroup.java:4651)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2050)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1807)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1044)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5818)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:768)
            at android.view.Choreographer.doCallbacks(Choreographer.java:581)
            at android.view.Choreographer.doFrame(Choreographer.java:551)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:754)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5333)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:711)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by Malinskiy** [comment]
Hi @ayyb1988,

this is an issue with [another library](https://github.com/eowise/recyclerview-stickyheaders), but it's deprecated and unsupported as I can see. If you'd like to reimplement or fix this - you are welcome :)
