### ISSUE TITLE
ViewStub must have a valid layoutResource

### ISSUE THREAD

**Issue by osemen-remit** [Malinskiy/SuperRecyclerView#56]
Hi,
Did you do any updates regarding ViewStubs recently? I'm getting this error but everithuing was ok yesterday:

```
     Caused by: java.lang.IllegalArgumentException: ViewStub must have a valid layoutResource
            at android.view.ViewStub.inflate(ViewStub.java:284)
            at android.view.ViewStub.setVisibility(ViewStub.java:235)
            at com.malinskiy.superrecyclerview.SuperRecyclerView.setAdapterInternal(SuperRecyclerView.java:299)
            at com.malinskiy.superrecyclerview.SuperRecyclerView.setAdapter(SuperRecyclerView.java:322)
            at se.memry.android.ui.feed.FeedActivity.onCreate(FeedActivity.java:280)
```

I'm using '+' version im my gradle file in order to be up to date. So probably it might be related to some changes in lib.

**Comment by Malinskiy** [comment]
Hi @osemen-remit,

thanks for the issue. Could you please check this on the hotfix branch? 
I think SRV is trying to call setVisibility on ViewStub when ViewStub is not actually inflated (you don't seem to have empty layout).

**Comment by osemen-remit** [comment]
Hi @Malinskiy, 
You are right, it happens when SRV is trying to call setVisibility on ViewStub for empty view.
Is it possible to pick a build from branch in my gradle file ? Or should I clone your repo ?

**Comment by Malinskiy** [comment]
@osemen-remit you should clone the branch and include it as `compile project(':SuperRecyclerView')` in your build.gradle instead of the version that is in mavencentral

**Comment by osemen-remit** [comment]
Hi, sorry for delay. 
Now it works. But `getEmptyView()` returns null until ViewStub is inflated. I have `TextView` for empty view and I would like to set custom typeface to it. It is possible to do it only from code. There is no way to know if empty view stub was inflated in order to call `getEmptyView()` and perform some manipulations on it. Probably in would be handy if some callback with inflated view is triggered when view stub is inflated.
Thanks.

**Comment by enginebai** [comment]
I encountered the same problem, the exception was gone after adding `app:layout_empty="@layout/view_empty"` to SRV.
